/**
 * Departamentos y municipios principales de Colombia.
 * Códigos DANE 2024. Lista curada con cobertura aproximada del 95% de la
 * población (capitales + cabeceras municipales principales). Para municipios
 * pequeños no listados, el formulario permite escritura libre como fallback.
 *
 * IMPORTANTE: Este archivo se carga sólo en /checkout (dynamic import).
 * No agregar imports aquí.
 */

export interface Department {
  /** Código DANE de 2 dígitos. */
  code: string;
  /** Nombre oficial del departamento. */
  name: string;
  /** Municipios principales (cabeceras + ciudades intermedias relevantes). */
  cities: string[];
}

export const COLOMBIA_DEPARTMENTS: Department[] = [
  {
    code: "11",
    name: "Bogotá D.C.",
    cities: ["Bogotá"],
  },
  {
    code: "05",
    name: "Antioquia",
    cities: [
      "Medellín",
      "Bello",
      "Envigado",
      "Itagüí",
      "Sabaneta",
      "Rionegro",
      "La Estrella",
      "Caldas",
      "Copacabana",
      "Girardota",
      "Apartadó",
      "Turbo",
      "Chigorodó",
      "Carepa",
      "Necoclí",
      "Caucasia",
      "Yarumal",
      "Santa Rosa de Osos",
      "Sonsón",
      "La Ceja",
      "Marinilla",
      "El Carmen de Viboral",
      "Guarne",
      "Santuario",
      "El Retiro",
      "Amalfi",
      "Yolombó",
      "Puerto Berrío",
      "Puerto Triunfo",
      "Andes",
      "Jardín",
      "Salgar",
      "Urrao",
      "Concordia",
      "Frontino",
      "Dabeiba",
    ],
  },
  {
    code: "08",
    name: "Atlántico",
    cities: [
      "Barranquilla",
      "Soledad",
      "Malambo",
      "Sabanagrande",
      "Sabanalarga",
      "Galapa",
      "Puerto Colombia",
      "Baranoa",
      "Palmar de Varela",
      "Ponedera",
      "Polonuevo",
      "Repelón",
      "Santo Tomás",
      "Tubará",
      "Usiacurí",
      "Manatí",
      "Luruaco",
      "Suan",
      "Juan de Acosta",
      "Piojó",
      "Candelaria",
      "Campo de la Cruz",
      "Santa Lucía",
    ],
  },
  {
    code: "13",
    name: "Bolívar",
    cities: [
      "Cartagena",
      "Turbaco",
      "Arjona",
      "Magangué",
      "El Carmen de Bolívar",
      "Turbaná",
      "Mahates",
      "San Juan Nepomuceno",
      "Santa Rosa",
      "Villanueva",
      "San Pablo",
      "Mompox",
      "San Jacinto",
      "Calamar",
      "María la Baja",
      "Clemencia",
      "San Estanislao",
      "Soplaviento",
      "Achí",
      "Tiquisio",
      "Simití",
      "Santa Rosa del Sur",
      "Cantagallo",
      "Morales",
      "Norosí",
      "Río Viejo",
      "Pinillos",
      "Margarita",
      "Talaigua Nuevo",
      "Cicuco",
      "Hatillo de Loba",
      "San Martín de Loba",
      "Barranco de Loba",
      "Altos del Rosario",
    ],
  },
  {
    code: "15",
    name: "Boyacá",
    cities: [
      "Tunja",
      "Duitama",
      "Sogamoso",
      "Chiquinquirá",
      "Paipa",
      "Villa de Leyva",
      "Garagoa",
      "Moniquirá",
      "Puerto Boyacá",
      "Samacá",
      "Tibasosa",
      "Nobsa",
      "Cómbita",
      "Soatá",
      "Otanche",
      "Pauna",
      "Saboyá",
      "Ráquira",
      "San Pablo de Borbur",
      "Briceño",
      "Buenavista",
      "Maripí",
      "Muzo",
      "Quípama",
      "Tinjacá",
      "Sutamarchán",
      "Sáchica",
      "Cucaita",
      "Sora",
      "Toca",
      "Siachoque",
    ],
  },
  {
    code: "17",
    name: "Caldas",
    cities: [
      "Manizales",
      "La Dorada",
      "Chinchiná",
      "Villamaría",
      "Anserma",
      "Riosucio",
      "Supía",
      "Salamina",
      "Aguadas",
      "Pácora",
      "Aranzazu",
      "Filadelfia",
      "Neira",
      "Marmato",
      "Belalcázar",
      "Risaralda",
      "Viterbo",
      "San José",
      "Palestina",
      "Marquetalia",
      "Manzanares",
      "Pensilvania",
      "Marulanda",
      "Norcasia",
      "Samaná",
      "Victoria",
      "La Merced",
    ],
  },
  {
    code: "18",
    name: "Caquetá",
    cities: [
      "Florencia",
      "San Vicente del Caguán",
      "Belén de los Andaquíes",
      "Curillo",
      "El Doncello",
      "El Paujil",
      "La Montañita",
      "Milán",
      "Morelia",
      "Puerto Rico",
      "San José del Fragua",
      "Solano",
      "Solita",
      "Valparaíso",
      "Cartagena del Chairá",
      "Albania",
    ],
  },
  {
    code: "19",
    name: "Cauca",
    cities: [
      "Popayán",
      "Santander de Quilichao",
      "Puerto Tejada",
      "Patía",
      "Caloto",
      "Corinto",
      "Miranda",
      "Padilla",
      "Villa Rica",
      "Guapi",
      "Timbío",
      "Cajibío",
      "Piendamó",
      "Silvia",
      "Morales",
      "Bolívar",
      "Mercaderes",
      "Argelia",
      "Balboa",
      "El Tambo",
      "La Sierra",
      "La Vega",
      "López de Micay",
      "Timbiquí",
      "Buenos Aires",
      "Suárez",
      "Sotará",
      "Inzá",
      "Páez",
      "Totoró",
      "Toribío",
      "Jambaló",
      "Caldono",
      "Almaguer",
    ],
  },
  {
    code: "20",
    name: "Cesar",
    cities: [
      "Valledupar",
      "Aguachica",
      "Codazzi",
      "Bosconia",
      "Curumaní",
      "El Copey",
      "La Jagua de Ibirico",
      "San Diego",
      "Chiriguaná",
      "La Paz",
      "Manaure Balcón del Cesar",
      "Pueblo Bello",
      "Astrea",
      "Becerril",
      "Chimichagua",
      "El Paso",
      "Gamarra",
      "González",
      "La Gloria",
      "Pailitas",
      "Pelaya",
      "Río de Oro",
      "San Alberto",
      "San Martín",
      "Tamalameque",
    ],
  },
  {
    code: "23",
    name: "Córdoba",
    cities: [
      "Montería",
      "Lorica",
      "Cereté",
      "Sahagún",
      "Planeta Rica",
      "Tierralta",
      "Montelíbano",
      "Ciénaga de Oro",
      "Ayapel",
      "Buenavista",
      "Chinú",
      "Pueblo Nuevo",
      "Puerto Libertador",
      "San Andrés de Sotavento",
      "San Antero",
      "San Bernardo del Viento",
      "San Carlos",
      "San José de Uré",
      "San Pelayo",
      "Tuchín",
      "Valencia",
      "Canalete",
      "Cotorra",
      "La Apartada",
      "Los Córdobas",
      "Momil",
      "Moñitos",
      "Puerto Escondido",
      "Purísima",
    ],
  },
  {
    code: "25",
    name: "Cundinamarca",
    cities: [
      "Soacha",
      "Facatativá",
      "Zipaquirá",
      "Chía",
      "Mosquera",
      "Madrid",
      "Funza",
      "Cajicá",
      "Girardot",
      "Fusagasugá",
      "Ubaté",
      "La Calera",
      "Cota",
      "Tocancipá",
      "Sopó",
      "Tabio",
      "Tenjo",
      "Sibaté",
      "Gachancipá",
      "Chocontá",
      "Villeta",
      "La Mesa",
      "Anapoima",
      "Tocaima",
      "Apulo",
      "Cachipay",
      "El Colegio",
      "San Antonio del Tequendama",
      "Tena",
      "Pacho",
      "Yacopí",
      "Caparrapí",
      "La Vega",
      "San Francisco",
      "Vergara",
      "Útica",
      "Quebradanegra",
      "Nimaima",
      "Nocaima",
      "Sasaima",
      "Albán",
      "Bituima",
      "Guayabal de Síquima",
      "Anolaima",
      "Zipacón",
      "El Rosal",
      "Subachoque",
      "San Cayetano",
      "Topaipí",
      "Paime",
      "Villagómez",
      "Ricaurte",
      "Agua de Dios",
      "Nilo",
      "Tibacuy",
      "Pasca",
      "Granada",
      "Silvania",
      "Arbeláez",
      "Pandi",
      "San Bernardo",
      "Cabrera",
      "Venecia",
      "Guataquí",
      "Beltrán",
      "Jerusalén",
      "Pulí",
      "San Juan de Rioseco",
      "Chaguaní",
      "Tibirita",
      "Manta",
      "Machetá",
      "Sesquilé",
      "Suesca",
      "Cucunubá",
      "Tausa",
      "Carmen de Carupa",
      "Susa",
      "Simijaca",
      "Fúquene",
      "Lenguazaque",
      "Guachetá",
      "Villapinzón",
      "Nemocón",
      "Guatavita",
      "Junín",
      "Gachetá",
      "Gama",
      "Ubalá",
      "Gachalá",
      "Medina",
      "Paratebueno",
      "Cáqueza",
      "Quetame",
      "Une",
      "Chipaque",
      "Fómeque",
      "Guayabetal",
      "Gutiérrez",
      "Choachí",
      "Ubaque",
    ],
  },
  {
    code: "27",
    name: "Chocó",
    cities: [
      "Quibdó",
      "Istmina",
      "Tadó",
      "Condoto",
      "Bahía Solano",
      "Nuquí",
      "Acandí",
      "Unguía",
      "Riosucio",
      "Carmen del Darién",
      "Bojayá",
      "Lloró",
      "Atrato",
      "Bagadó",
      "Cantón de San Pablo",
      "Cértegui",
      "Litoral del San Juan",
      "Medio Atrato",
      "Medio Baudó",
      "Medio San Juan",
      "Nóvita",
      "El Carmen de Atrato",
      "Río Iró",
      "Río Quito",
      "San José del Palmar",
      "Sipí",
      "Bajo Baudó",
      "Alto Baudó",
      "El Cantón del San Pablo",
      "Juradó",
    ],
  },
  {
    code: "41",
    name: "Huila",
    cities: [
      "Neiva",
      "Pitalito",
      "Garzón",
      "La Plata",
      "Campoalegre",
      "San Agustín",
      "Aipe",
      "Algeciras",
      "Gigante",
      "Hobo",
      "Íquira",
      "Isnos",
      "Palermo",
      "Palestina",
      "Rivera",
      "Saladoblanco",
      "Suaza",
      "Tarqui",
      "Tello",
      "Teruel",
      "Tesalia",
      "Timaná",
      "Yaguará",
      "Acevedo",
      "Agrado",
      "Altamira",
      "Baraya",
      "Colombia",
      "Elías",
      "Guadalupe",
      "Nátaga",
      "Oporapa",
      "Paicol",
      "Pital",
      "Santa María",
      "Villavieja",
    ],
  },
  {
    code: "44",
    name: "La Guajira",
    cities: [
      "Riohacha",
      "Maicao",
      "Uribia",
      "Manaure",
      "San Juan del Cesar",
      "Villanueva",
      "Fonseca",
      "Barrancas",
      "Albania",
      "Dibulla",
      "El Molino",
      "Hatonuevo",
      "La Jagua del Pilar",
      "Distracción",
      "Urumita",
    ],
  },
  {
    code: "47",
    name: "Magdalena",
    cities: [
      "Santa Marta",
      "Ciénaga",
      "Fundación",
      "Aracataca",
      "El Banco",
      "Plato",
      "Pivijay",
      "Zona Bananera",
      "Algarrobo",
      "Ariguaní",
      "Cerro de San Antonio",
      "Chivolo",
      "Concordia",
      "El Piñón",
      "El Retén",
      "Guamal",
      "Nueva Granada",
      "Pedraza",
      "Pijiño del Carmen",
      "Pueblo Viejo",
      "Remolino",
      "Sabanas de San Ángel",
      "Salamina",
      "San Sebastián de Buenavista",
      "San Zenón",
      "Santa Ana",
      "Santa Bárbara de Pinto",
      "Sitionuevo",
      "Tenerife",
      "Zapayán",
    ],
  },
  {
    code: "50",
    name: "Meta",
    cities: [
      "Villavicencio",
      "Acacías",
      "Granada",
      "Puerto López",
      "Puerto Gaitán",
      "Cumaral",
      "San Martín",
      "Restrepo",
      "El Castillo",
      "El Dorado",
      "Fuente de Oro",
      "Guamal",
      "Mapiripán",
      "Mesetas",
      "La Macarena",
      "Lejanías",
      "Puerto Concordia",
      "Puerto Lleras",
      "Puerto Rico",
      "Cubarral",
      "Cabuyaro",
      "San Carlos de Guaroa",
      "San Juan de Arama",
      "San Juanito",
      "Uribe",
      "Vista Hermosa",
      "Castilla la Nueva",
            "Barranca de Upía",
    ],
  },
  {
    code: "52",
    name: "Nariño",
    cities: [
      "Pasto",
      "Tumaco",
      "Ipiales",
      "Túquerres",
      "Samaniego",
      "La Unión",
      "Sandoná",
      "Buesaco",
      "Chachagüí",
      "El Charco",
      "Barbacoas",
      "Ricaurte",
      "Mallama",
      "Cumbal",
      "Guachucal",
      "Aldana",
      "Pupiales",
      "Iles",
      "Ospina",
      "Imués",
      "Sapuyes",
      "Funes",
      "Potosí",
      "Córdoba",
      "Puerres",
      "Contadero",
      "Gualmatán",
      "Yacuanquer",
      "Tangua",
      "Nariño",
      "La Florida",
      "Ancuyá",
      "Consaca",
      "Linares",
      "Los Andes",
      "El Peñol",
      "Taminango",
      "El Tambo",
      "El Rosario",
      "Leiva",
      "Policarpa",
      "Cumbitara",
      "Magüí Payán",
      "Roberto Payán",
      "Olaya Herrera",
      "Mosquera",
      "Francisco Pizarro",
      "La Tola",
      "Santa Bárbara",
      "San Andrés de Tumaco",
      "Albán",
      "Belén",
      "Colón",
      "El Tablón de Gómez",
      "La Cruz",
      "San Bernardo",
      "San José de Albán",
      "San Lorenzo",
      "San Pablo",
      "San Pedro de Cartago",
      "Arboleda",
      "El Peñol",
    ],
  },
  {
    code: "54",
    name: "Norte de Santander",
    cities: [
      "Cúcuta",
      "Ocaña",
      "Pamplona",
      "Villa del Rosario",
      "Los Patios",
      "El Zulia",
      "Tibú",
      "Ábrego",
      "San Cayetano",
      "Sardinata",
      "Salazar",
      "Chinácota",
      "Bochalema",
      "Cáchira",
      "Convención",
      "Cucutilla",
      "Durania",
      "El Carmen",
      "El Tarra",
      "Hacarí",
      "Herrán",
      "La Esperanza",
      "La Playa",
      "Labateca",
      "Lourdes",
      "Mutiscua",
      "Pamplonita",
      "Puerto Santander",
      "Ragonvalia",
      "San Calixto",
      "Santiago",
      "Silos",
      "Teorama",
      "Toledo",
      "Villa Caro",
    ],
  },
  {
    code: "63",
    name: "Quindío",
    cities: [
      "Armenia",
      "Calarcá",
      "La Tebaida",
      "Montenegro",
      "Quimbaya",
      "Circasia",
      "Salento",
      "Filandia",
      "Pijao",
      "Génova",
      "Córdoba",
      "Buenavista",
    ],
  },
  {
    code: "66",
    name: "Risaralda",
    cities: [
      "Pereira",
      "Dosquebradas",
      "Santa Rosa de Cabal",
      "La Virginia",
      "Belén de Umbría",
      "Marsella",
      "Apía",
      "Balboa",
      "Guática",
      "La Celia",
      "Mistrató",
      "Pueblo Rico",
      "Quinchía",
      "Santuario",
    ],
  },
  {
    code: "68",
    name: "Santander",
    cities: [
      "Bucaramanga",
      "Floridablanca",
      "Girón",
      "Piedecuesta",
      "Barrancabermeja",
      "San Gil",
      "Socorro",
      "Málaga",
      "Vélez",
      "Lebrija",
      "Rionegro",
      "Sabana de Torres",
      "San Vicente de Chucurí",
      "El Playón",
      "Puerto Wilches",
      "Suaita",
      "Charalá",
      "Aratoca",
      "Curití",
      "Mogotes",
      "Onzaga",
      "San Joaquín",
      "Villanueva",
      "Barichara",
      "Cabrera",
      "Cepitá",
      "Galán",
      "Jordán",
      "Páramo",
      "Pinchote",
      "Valle de San José",
      "Confines",
      "Contratación",
      "El Guacamayo",
      "Encino",
      "Gambita",
      "Guadalupe",
      "Hato",
      "Oiba",
      "Palmar",
      "Palmas del Socorro",
      "Simacota",
      "Guapotá",
      "San Andrés",
      "Tona",
      "Matanza",
      "Surata",
      "California",
      "Charta",
      "Vetas",
      "Bolívar",
      "El Peñón",
      "La Belleza",
      "Sucre",
      "Florián",
      "Albania",
      "Jesús María",
      "La Paz",
      "Puente Nacional",
      "Chipatá",
      "Guavatá",
      "Güepsa",
      "San Benito",
    ],
  },
  {
    code: "70",
    name: "Sucre",
    cities: [
      "Sincelejo",
      "Corozal",
      "Sampués",
      "Tolú",
      "San Marcos",
      "Sincé",
      "Coveñas",
      "San Onofre",
      "Toluviejo",
      "Morroa",
      "Los Palmitos",
      "Ovejas",
      "Chalán",
      "Colosó",
      "Galeras",
      "Buenavista",
      "El Roble",
      "Caimito",
      "La Unión",
      "San Benito Abad",
      "San Pedro",
      "San Luis de Sincé",
      "Majagual",
      "Sucre",
      "Guaranda",
      "Palmito",
    ],
  },
  {
    code: "73",
    name: "Tolima",
    cities: [
      "Ibagué",
      "Espinal",
      "Melgar",
      "Honda",
      "Líbano",
      "Chaparral",
      "Mariquita",
      "Fresno",
      "Purificación",
      "Cajamarca",
      "Flandes",
      "Guamo",
      "Saldaña",
      "Coyaima",
      "Natagaima",
      "Ortega",
      "Rovira",
      "San Antonio",
      "San Luis",
      "Suárez",
      "Valle de San Juan",
      "Ambalema",
      "Anzoátegui",
      "Armero",
      "Ataco",
      "Carmen de Apicalá",
      "Casabianca",
      "Coello",
      "Cunday",
      "Dolores",
      "Falan",
      "Herveo",
      "Icononzo",
      "Lérida",
      "Murillo",
      "Palocabildo",
      "Piedras",
      "Planadas",
      "Prado",
      "Rioblanco",
      "Roncesvalles",
      "San Sebastián de Mariquita",
      "Santa Isabel",
      "Venadillo",
      "Villahermosa",
      "Villarrica",
      "Alpujarra",
      "Alvarado",
    ],
  },
  {
    code: "76",
    name: "Valle del Cauca",
    cities: [
      "Cali",
      "Palmira",
      "Buenaventura",
      "Tuluá",
      "Cartago",
      "Buga",
      "Jamundí",
      "Yumbo",
      "Florida",
      "Pradera",
      "Sevilla",
      "Caicedonia",
      "Zarzal",
      "Roldanillo",
      "La Unión",
      "Andalucía",
      "Bugalagrande",
      "Calima",
      "Candelaria",
      "Dagua",
      "El Águila",
      "El Cairo",
      "El Cerrito",
      "El Dovio",
      "Ginebra",
      "Guacarí",
      "La Cumbre",
      "La Victoria",
      "Obando",
      "Restrepo",
      "Riofrío",
      "San Pedro",
      "Toro",
      "Trujillo",
      "Ulloa",
      "Versalles",
      "Vijes",
      "Yotoco",
      "Alcalá",
      "Ansermanuevo",
      "Argelia",
      "Bolívar",
    ],
  },
  {
    code: "81",
    name: "Arauca",
    cities: [
      "Arauca",
      "Saravena",
      "Tame",
      "Arauquita",
      "Fortul",
      "Puerto Rondón",
      "Cravo Norte",
    ],
  },
  {
    code: "85",
    name: "Casanare",
    cities: [
      "Yopal",
      "Aguazul",
      "Tauramena",
      "Villanueva",
      "Monterrey",
      "Paz de Ariporo",
      "Maní",
      "Trinidad",
      "Pore",
      "Hato Corozal",
      "Nunchía",
      "Orocué",
      "San Luis de Palenque",
      "Sácama",
      "Chámeza",
      "La Salina",
      "Recetor",
      "Sabanalarga",
      "Támara",
    ],
  },
  {
    code: "86",
    name: "Putumayo",
    cities: [
      "Mocoa",
      "Puerto Asís",
      "Orito",
      "Valle del Guamuez",
      "Villagarzón",
      "San Miguel",
      "Sibundoy",
      "Colón",
      "Santiago",
      "San Francisco",
      "Puerto Caicedo",
      "Puerto Guzmán",
      "Puerto Leguízamo",
    ],
  },
  {
    code: "88",
    name: "San Andrés y Providencia",
    cities: ["San Andrés", "Providencia"],
  },
  {
    code: "91",
    name: "Amazonas",
    cities: [
      "Leticia",
      "Puerto Nariño",
      "Tarapacá",
      "La Pedrera",
      "La Chorrera",
      "El Encanto",
      "Puerto Alegría",
      "Puerto Arica",
      "Puerto Santander",
      "Mirití - Paraná",
    ],
  },
  {
    code: "94",
    name: "Guainía",
    cities: [
      "Inírida",
      "Barranco Minas",
      "Mapiripana",
      "San Felipe",
      "Puerto Colombia",
      "La Guadalupe",
      "Cacahual",
      "Pana Pana",
      "Morichal",
    ],
  },
  {
    code: "95",
    name: "Guaviare",
    cities: [
      "San José del Guaviare",
      "Calamar",
      "El Retorno",
      "Miraflores",
    ],
  },
  {
    code: "97",
    name: "Vaupés",
    cities: [
      "Mitú",
      "Carurú",
      "Pacoa",
      "Taraira",
      "Papunaua",
      "Yavaraté",
    ],
  },
  {
    code: "99",
    name: "Vichada",
    cities: [
      "Puerto Carreño",
      "La Primavera",
      "Santa Rosalía",
      "Cumaribo",
    ],
  },
];

/**
 * Devuelve las ciudades de un departamento por su nombre.
 * Útil para poblar el segundo dropdown cuando cambia el departamento.
 */
export function getCitiesForDepartment(
  departmentName: string,
): readonly string[] {
  const dept = COLOMBIA_DEPARTMENTS.find((d) => d.name === departmentName);
  return dept?.cities ?? [];
}

/** Nombres de los departamentos para uso rápido en selects. */
export const DEPARTMENT_NAMES: readonly string[] = COLOMBIA_DEPARTMENTS.map(
  (d) => d.name,
);